version: 0.0
os: linux
files:
  - source: Config/config.txt
    destination: /webapps/Config
  - source: source
    destination: /webapps/myApp
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
