version: 0.0
os: linux
files:
  - source: /
    destination: /opt/application/bestbuy
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: /beforeinstall.sh
    - timeout: 180
  AfterInstall:
    - location: /afterinstall.sh
      timeout: 180
